### ISSUE TITLE
Support multiple os's

### ISSUE THREAD

**Issue by ismacaulay** [nitehawck/dem#3]

**Comment by ismacaulay** [comment]
A potiential way to specify platforms:

dem.yaml
```
config:
   remote_locations: ['/repo']
   arch: x86_64

all:
   qt:
      version: 5.6.0
      type: archive

linux:
...
```

Then search the following based on the platform
'/repo/linux/centos7/x86_64'
'/repo/linux/rhel7/x86_64'
'/repo/linux/ubuntu16/x86_64'
'/repo/linux'
'/repo/windows'
'/repo/all'
